### ISSUE TITLE
Changed IE settings

### ISSUE THREAD

**Issue by 0xsauby** [pentestgeek/smbexec#121]
I recently used smbexec against several hosts, in order to dump hashes from workstations, using a privileged domain account. I noticed that it changed IE settings, specifically default url to about:blank, on all the hosts. Any idea why that would be?

**Comment by smilingraccoon** [comment]
Are you sure smbexec was doing it? The hashdump uses winexe to create a PSExec style service, dumps registry items to the temp directory, downloads them with smbclient, uploads WCE to the temp directory, execs that, and deletes it and the registry files. Nothing should be interacting with anything IE. Any more information you could provide would be helpful and ill look into it but I honestly have no clue how that could have happened from smbexec.

**Comment by 0xsauby** [comment]
Yeah thats my understanding of the tool as well and I have used it numerous times without any issues. I re-ran it against selective targets to confirm the issue and it changed the IE setting again. I'll debug it more tomorrow and get back to you. Thanks.

**Comment by smilingraccoon** [comment]
There are debug files (within the log folder) that show exactly what commands are run against the target as well. You can just doing them manually one by one to see which one potentially did it.

**Comment by brav0hax** [comment]
Pretty sure we can close this. This behavior doesnt seem to be anything that would be born from our tool.  smbclient cant do this. Winexe may be able to based on the command being sent, but again our commands simply backup the registry for HLKM SAM, SYS, Sec...nothing else
