### ISSUE TITLE
kali 20167.1 rolling: smb_static library not found in winexe compile

### ISSUE THREAD

**Issue by Brockway** [pentestgeek/smbexec#125]
Not sure if you guys are still actively supporting smbexec. I am playing with the Kali Rolling base image, my tools install script bailed out during smbexec. Baselined it with fresh install with apt update and install from the rolling deb and deb-src repos, getting this:

[ 239/3774] Compiling IDL librpc/idl/atsvc.idl
Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at /tmp/smbexec-inst/samba/pidl/lib/Parse/Pidl/ODL.pm line 73.
Compilation failed in require at /tmp/smbexec-inst/samba/pidl/pidl line 412.
BEGIN failed--compilation aborted at /tmp/smbexec-inst/samba/pidl/pidl line 412.
Waf: Leaving directory `/tmp/smbexec-inst/samba/bin'
Build failed:  -> task failed (err #255): 
	{task: PIDL_ATSVC atsvc.idl,CUtil.pm,Compat.pm,Dump.pm,Expr.pm,IDL.pm,NDR.pm,ODL.pm,ClientNDR.pm,ServerNDR.pm,Header.pm,Proxy.pm,Stub.pm,Header.pm,Client.pm,Parser.pm,Server.pm,Python.pm,TDR.pm,Template.pm,Samba4.pm,Typelist.pm,Util.pm,Conformance.pm,NDR.pm,Pidl.pm,Driver.pm -> atsvc.h,ndr_atsvc.c,ndr_atsvc.h,srv_atsvc.c,srv_atsvc.h,ndr_atsvc_s.c,ndr_atsvc_c.c,ndr_atsvc_c.h,py_atsvc.c}
Checking for library smb_static                                 : not found 
Build of static winexe                                          : disabled 
Cannot continue! Please install required files for shared winexe or provide samba source path for static winexe(--samba-dir option).
(complete log in /tmp/smbexec-inst/winexe/source/build/config.log)
cp: cannot stat ‘/tmp/smbexec-inst/winexe/source/build/winexe-static’: No such file or directory
[!] smbwinexe didn't install properly. Make sure you have prereqs installed...

Let me know if this is something you may look into.

Thanks, gents.

**Comment by Brockway** [comment]
fat finger, no 7 in issue title

**Comment by dginther** [comment]
I am having this same issue

**Comment by brav0hax** [comment]
I dont really work on this anymore, sorry. But I do have a
recommendation...just create a sym link to pth-winexe and pth-smbclient in
the proper folder for smbexec. This will get around any issues with
compiling and allow you to use hash passing.

The only reason I compiled in the install was to patch for hash passing.

The sym links will work :)

Thanks,
Eric

**Comment by dginther** [comment]
Thanks! That solved this.

**Comment by hatlord** [comment]
Hey guys, what should the symlinks be? Just trying to get this running after upgrading to Kali rolling! Any chance the code will be updated to work in Kali rolling out of the box? 
Thanks :)

**Comment by Brockway** [comment]
from smbexec\progs:

ln -s /usr/bin/pth-winexe smbwinexe
ln -s /usr/bin/pth-smbclient smbexeclient

anyone else who moved past this issue getting errors making esedbtools? I'll open a different issue.
